server:
  port: 8083
  servlet:
    context-path: /geometry
spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
  jackson:
    serialization.write-dates-as-timestamps: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false
logging:
  level:
    root: info
    org:
      hibernate:
        type: trace

googleApiKey: AIzaSyD52V6H98iYDJ-p5_Np7f37aNnTt13kKtg
kakaoApiKey: 8d39467879a51b1cfd18613970929af4