spring:
  datasource:
    hikari: #https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      jdbcUrl: jdbc:mysql://34.64.95.80:3306/pinstagram?useUnicode=true&characterEncoding=utf8
      username: root
      password: test1234
      driver-class-name: com.mysql.jdbc.Driver
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 40
      maximumPoolSize: 40
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: false
